"""empty message

Revision ID: 947eef5bdae9
Revises: 8b3efea40e88
Create Date: 2022-08-09 14:26:30.063770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947eef5bdae9'
down_revision = '8b3efea40e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
